AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: >
  {{ cookiecutter.project_name }}

  {{ cookiecutter.project_short_description }}

Globals:
  Function:
    Runtime: python3.7
    Environment:
      Variables:
        LOG_LEVEL: INFO
    Timeout: 5

Resources:
  Up:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: app
      Handler: handler.handle
      Tracing: Active
      Policies:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AWSXrayWriteOnlyAccess
